<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Accessibility feedback_jfN4p</name>
   <tag></tag>
   <elementGuidId>f578e796-1c6d-4f19-b1b1-1eace7762fb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.jfN4p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logo']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e1832cb4-1a50-4be2-8124-4a116c95c131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jfN4p</value>
      <webElementGuid>53f49b19-dc2f-4635-bb5a-d75d9dfa32d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png</value>
      <webElementGuid>9f1c3028-6e2c-4a48-b650-86cef8367f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>e575bb28-ecfe-4cb9-9772-26b1a6d540b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>8a33e795-4e2b-4f10-9140-5f25944e1e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>92</value>
      <webElementGuid>609e0a09-f71d-4aa3-97d0-9928bf172834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csiid</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>971adeb1-764b-422a-a4dd-d0d04266b778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-atf</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f004f68b-26dd-44a2-a3ce-d57f447789d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo&quot;)/img[@class=&quot;jfN4p&quot;]</value>
      <webElementGuid>17df85b4-a5b0-4d02-a3d0-41b598750b2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='logo']/img</value>
      <webElementGuid>d9e4261c-ffa5-4058-a59d-c88f4cd3c220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Google']</value>
      <webElementGuid>9b51a506-1976-4147-a474-a6d4d5854ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>6d6ebce0-da82-4d47-9004-5836fe1d9e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png' and @alt = 'Google']</value>
      <webElementGuid>883a989d-3103-4c4a-91c6-94f7f2f22a62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
