<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Leave_fui-Icon-filled ___1vjqft9 fjseox_745f53</name>
   <tag></tag>
   <elementGuidId>7c3971d9-7730-4040-b2ea-1051875a3d2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#share-button > div.fui-Flex.___1ks0vaw.f22iagw.f1k3vf2q.fpjrses.f16p6fhc.fqerorx.f1pztt34 > div.ui-toolbar__itemicon > svg.fui-Icon-filled.___1vjqft9.fjseox.fez10in.fg4l7m0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::*[name()='svg'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>755b83e6-9b8e-4dab-a30e-8dfe4c486c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fui-Icon-filled ___1vjqft9 fjseox fez10in fg4l7m0</value>
      <webElementGuid>61e56f75-bcec-4834-9dba-ca317faf13ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>2f9ced4a-e347-4ddc-991f-ed495b50ebb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b4e177a9-6484-4a01-add1-37425afe75f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>ac7e47b8-e83d-4e62-82c5-9554fcc87f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>d9936575-8617-40c6-b426-ef8de9dbd974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 20 20</value>
      <webElementGuid>6903eb14-71fe-47c0-a6f0-9d31a7344b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>4576721c-b010-427f-97b5-e00d285ac2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bb68c8d2-6684-4f4b-bf47-d3c97af69d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;share-button&quot;)/div[@class=&quot;fui-Flex ___1ks0vaw f22iagw f1k3vf2q fpjrses f16p6fhc fqerorx f1pztt34&quot;]/div[@class=&quot;ui-toolbar__itemicon&quot;]/svg[@class=&quot;fui-Icon-filled ___1vjqft9 fjseox fez10in fg4l7m0&quot;]</value>
      <webElementGuid>d1970263-fdf1-4908-878b-1deed5c59fa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>1064074f-1fb5-4bd7-a18e-3231982db240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Luqman ', &quot;'&quot;, 'Afeefi Marahat')])[1]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>3011fb57-bf70-40e8-9ca2-1dbf012250cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
