<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Leave_fui-Icon-filled ___12fm75w f1w7gp_94f887</name>
   <tag></tag>
   <elementGuidId>81bff85d-bcdf-435e-b05e-14f5c0e3799c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#microphone-button > div.fui-Flex.___1ks0vaw.f22iagw.f1k3vf2q.fpjrses.f16p6fhc.fqerorx.f1pztt34 > div.ui-toolbar__itemicon > svg.fui-Icon-filled.___12fm75w.f1w7gpdv.fez10in.fg4l7m0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::*[name()='svg'][4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>44fae0bf-f741-4a2a-b9f2-241cb63efd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fui-Icon-filled ___12fm75w f1w7gpdv fez10in fg4l7m0</value>
      <webElementGuid>e1fdc956-2a4d-4827-bed4-fad9d94076fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>71430b09-f3e9-4d13-8e7e-e380482e55d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>03685296-b5f5-4da6-aadf-59a5c15ba9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>42064d56-14a3-4c0a-acbe-8795b8951995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>71a18831-0316-4f96-bfd0-40adea4302da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 20 20</value>
      <webElementGuid>6ba1deba-121f-442b-a402-cad97ddff649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>35f3d511-1b75-4292-9ec3-00bf0f0364ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b23afeac-d4af-49aa-9b7d-a3c2625309f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;microphone-button&quot;)/div[@class=&quot;fui-Flex ___1ks0vaw f22iagw f1k3vf2q fpjrses f16p6fhc fqerorx f1pztt34&quot;]/div[@class=&quot;ui-toolbar__itemicon&quot;]/svg[@class=&quot;fui-Icon-filled ___12fm75w f1w7gpdv fez10in fg4l7m0&quot;]</value>
      <webElementGuid>6ea6ed2a-2cc6-4118-b5f0-24b9673a1ac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>83e2ba33-4e17-4ef8-9528-8faf72cde275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zoom: 100%'])[1]/preceding::*[name()='svg'][6]</value>
      <webElementGuid>f9db5455-1580-446b-82d7-71541f622284</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
